#Profile for launching the .java app on host
#
# DB config
spring.datasource.url=jdbc:mysql://localhost:${HOST_DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# MQTT broker config
mqtt.broker.url=tcp://localhost:${HOST_MQTT_PORT}

# ?
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.web=debug